package com.server.server.enums.Notification;

public enum NotificationType {
    BOOKING_CONFIRMED, TOUR_APPROVAL_REQUIRED, TOUR_APPROVED, CANCELLATION_ALERT, ONE_WEEK_TRAVEL_REMINDER,
    SYSTEM_ALERT,
    REQUEST_CREATED,
    REQUEST_ASSIGNED,
    REQUEST_SOLVED,
    REQUEST_REJECTED,
    TOUR_COMPLETED
}